name: C Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v7
      with:
        pkgs: openssl
        triplet: x64-windows-release
    - name: Install cargo-c
      uses: taiki-e/cache-cargo-install-action@v2 
      with:
        tool: cargo-c
    - name: CBuild rice-proto
      run: cargo cbuild -p rice-proto --verbose
    - name: CBuild rice-io
      run: cargo cbuild -p rice-io --verbose
    - name: Browse files
      run: tree
